version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data-test
        target: /data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  producer-consumer:
    build: .
    ports:
      - "3000:3000"
volumes:
  redis-data-test: {}
