version: '3.7'
services:
  redis:
    container_name: redis
    hostname: redis
    image: sameersbn/redis:4.0.9-2
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data
        target: /data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASSWORD=${HTTP_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis-test:
    build: .
    image: nidkil/redis-test
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DEBUG=${REDIS_DEBUG}
    ports:
      - "3000:3000"
    depends_on:
      - redis
volumes:
  redis-data: {}
